language: ruby
rvm:
- 2.3.3
branches:
  only:
  - master
before_install:
- chmod u+x deploy_init.sh
- bash deploy_init.sh
- npm install
before_script:
- gulp jsmin_travis
script:
- bundle exec jekyll build
- gulp imagemin
before_deploy:
- chmod u+x deploy.sh
deploy:
  provider: script
  script: "./deploy.sh"
  skip_cleanup: true
sudo: false
env:
  global:
    secure: droz2A4SOaROBo+3rmDwyZvryUOMjVm1gBy7pYiWM0bma367KYqKkGtRqwvBBUQcUkfowvogEKpy4DMIYUqTxOy9or8OsRknhffYI4Ctt1USIYs8T+jN5e6LH0k98hP7SIB56NaAD3fhHWgODCHP8lamC3l1ddj/HWMrftckABJ1dG61Gma0z2R/qhc/0UD+J7Lytinma2XrulyiGelpuJVe9BhFTY/nh9QjzShp7I0tTwvbGEfSsfPtdyrmcI1j7eX9zuexvG4UCP7ABC3VsDwBzCR+U0r/wbEcEi5Et9N6f+7YChbbMC0lONTKIO4Os5qrjoZha7gP17H/rU1eJY5HbJnF7s6pbSduKRGWSBy/bPA5J4HvYzQeqAPG4hr0IimWystNAM6Bc7zymXXrY0pvBGG8NfTes/i2NdPsqnjnbuJTx09qRyw80N3ukbQPl2EArQR91DOiaEjhFc9I+mpZj1HQIlui24fjNLsM63/wQ9fadofNoWNpokJXkzhTkEHXh4Yo+tQEzBy0ELlBiT4Q0m0eiHrFLh7eQuHz88sOPHQNNnhnMnYyEXZyhUc96KKFQhXDXzFa72mxJYwasdLrdS5gbK1ONszfAKAOaw8o9u4589o5b/g9f/T/mCpIfbnnPnLFB6wGgXrW/h1D8FaiEpoaTy82OTC1KmzAOpg=
